services:
  db:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: securepass-dev-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: securepass-dev
    ports:
      - "5432:5432"
    volumes:
      - securepass-dev-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "securepass-dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  securepass-dev-pgdata:
